package com.example.demo.domain.entity.master;

import java.io.Serializable;

import lombok.Data;

@Data
public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uid
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_idx.thumb_nail
     *
     * @mbggenerated Fri Dec 02 13:52:50 CST 2016
     */
    private String thumbNail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_idx.avatar
     *
     * @mbggenerated Fri Dec 02 13:52:50 CST 2016
     */
    private String avatar;
   
   /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.user_id
   *
   * @mbg.generated Fri Nov 25 18:13:30 CST 2016
   */
  private String userId;
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column user_info.user_id
    *
    * @mbg.generated Fri Nov 25 18:13:30 CST 2016
    */
   private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_num
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_cardnum
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String idCardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String userName;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column user_info.user_name
    *
    * @mbg.generated Fri Nov 25 18:13:30 CST 2016
    */
   private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.branch_name
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String branchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.team_manager
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String teamManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.area
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.org_id
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.org_name
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_time
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private Long lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_version
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String lastLoginVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.channel
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private Integer channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_ip
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private String lastLoginIp;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    private static final long serialVersionUID = 1L;
    
    /**
     * 待处理录单数
     */
    private int toDealNum;
    
    /**
     * 待提交录单数
     */
    private int toSubmitNum;
    
    /**
     * 进度跟踪数
     */
    private int progressNum;
    
    /**
     * 已退回件数
     */
    private int backNum;
    
    /**
     * 登录次数
     */
    private int loginTimes;

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", userId=").append(userId);
        sb.append(", userAccount=").append(userAccount);
        sb.append(", password=").append(password);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", idCardnum=").append(idCardnum);
        sb.append(", userName=").append(userName);
        sb.append(", roleName=").append(roleName);
        sb.append(", branchName=").append(branchName);
        sb.append(", teamManager=").append(teamManager);
        sb.append(", city=").append(city);
        sb.append(", area=").append(area);
        sb.append(", orgId=").append(orgId);
        sb.append(", orgName=").append(orgName);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginVersion=").append(lastLoginVersion);
        sb.append(", channel=").append(channel);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfo other = (UserInfo) that;
        return (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserAccount() == null ? other.getUserAccount() == null : this.getUserAccount().equals(other.getUserAccount()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getIdCardnum() == null ? other.getIdCardnum() == null : this.getIdCardnum().equals(other.getIdCardnum()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getBranchName() == null ? other.getBranchName() == null : this.getBranchName().equals(other.getBranchName()))
            && (this.getTeamManager() == null ? other.getTeamManager() == null : this.getTeamManager().equals(other.getTeamManager()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastLoginTime() == null ? other.getLastLoginTime() == null : this.getLastLoginTime().equals(other.getLastLoginTime()))
            && (this.getLastLoginVersion() == null ? other.getLastLoginVersion() == null : this.getLastLoginVersion().equals(other.getLastLoginVersion()))
            && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
            && (this.getLastLoginIp() == null ? other.getLastLoginIp() == null : this.getLastLoginIp().equals(other.getLastLoginIp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Nov 25 18:13:30 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserAccount() == null) ? 0 : getUserAccount().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getIdCardnum() == null) ? 0 : getIdCardnum().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getBranchName() == null) ? 0 : getBranchName().hashCode());
        result = prime * result + ((getTeamManager() == null) ? 0 : getTeamManager().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
        result = prime * result + ((getLastLoginVersion() == null) ? 0 : getLastLoginVersion().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        result = prime * result + ((getLastLoginIp() == null) ? 0 : getLastLoginIp().hashCode());
        return result;
    }

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public int getToDealNum() {
		return toDealNum;
	}

	public void setToDealNum(int toDealNum) {
		this.toDealNum = toDealNum;
	}

	public int getToSubmitNum() {
		return toSubmitNum;
	}

	public void setToSubmitNum(int toSubmitNum) {
		this.toSubmitNum = toSubmitNum;
	}

	public int getProgressNum() {
		return progressNum;
	}

	public void setProgressNum(int progressNum) {
		this.progressNum = progressNum;
	}

	public int getBackNum() {
		return backNum;
	}

	public void setBackNum(int backNum) {
		this.backNum = backNum;
	}

	public String getThumbNail() {
		return thumbNail;
	}

	public void setThumbNail(String thumbNail) {
		this.thumbNail = thumbNail;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

}